Controllers/PaperAssignmentController.cs
using ExaminationPortal.App_Start;
using ExaminationPortal.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace ExaminationPortal.Controllers
{
    public class PaperAssignmentController : Controller
    {
        // GET: PaperAssignment
        [CheckSessionOutAttribute]
        public ActionResult Index()
        {
            try
            {
                var model = new StudentPaperDetail();
                DataTable dtDropDowntList = new DataTable();
                DataTable dtResult = new DataTable();

                #region Prepare dropdown data
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetAllStudentList_Get", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtDropDowntList);
                        }
                    }
                }
                ViewBag.StudentList = ToSelectList(dtDropDowntList, "UserID", "UserName");

                dtDropDowntList = new DataTable();
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetAllQuestionPaperList_Get", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtDropDowntList);
                        }
                    }
                }
                ViewBag.QPaperList = ToSelectList(dtDropDowntList, "QPaperID", "QPaperName");
                #endregion

                #region Get prepare list
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetAllStudentPaperDetailList_Get", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtResult);
                        }
                    }
                }
                #endregion

                #region Prepare data to rerurn into view
                if (dtResult != null && dtResult.Rows.Count > 0)
                {
                    List<StudentPaperDetail> list = (from dr in dtResult.AsEnumerable()
                                                     select new StudentPaperDetail()
                                                     {
                                                         StudentPaperDetailID = Convert.ToInt64(dr["StudentPaperDetailID"]),
                                                         QPaperID = Convert.ToInt64(dr["QPaperID"]),
                                                         UserID = Convert.ToInt64(dr["UserID"]),
                                                         QPaperStatus = dr["QPaperStatus"].ToString(),
                                                         UserName = dr["UserName"].ToString(),
                                                         PaperName = dr["QPaperName"].ToString(),
                                                         Marks = dr["Marks"] == DBNull.Value ? 0 : Convert.ToInt32(dr["Marks"])
                                                     }).ToList();

                    model.StudentPaperDetailList = list;
                }
                #endregion

                return View("~/views/PaperAssignment/index.cshtml", model);
            }
            catch (Exception ex)
            {
                return View("~/views/PaperAssignment/index.cshtml", new StudentPaperDetail());
            }
        }

        [NonAction]
        public SelectList ToSelectList(DataTable table, string valueField, string textField)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (DataRow row in table.Rows)
            {
                list.Add(new SelectListItem()
                {
                    Text = row[textField].ToString(),
                    Value = row[valueField].ToString()
                });
            }
            return new SelectList(list, "Value", "Text");
        }

        [HttpPost]
        [CheckSessionOutAttribute]
        public ActionResult AssignPaperToStudent(long UserID, long QPaperID)
        {
            try
            {
                if (UserID <= 0 || QPaperID <= 0 )
                    throw new Exception("Invalid parameter!!!");

                var model = new StudentPaperDetail();
                DataTable dtResult = new DataTable();

                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetStudentPaperDetail_GetByPaperAndUserIDs", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@QPaperID", QPaperID);
                        cmd.Parameters.AddWithValue("@UserID", UserID);
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtResult);
                        }
                    }
                }
                if (dtResult.Rows.Count > 0)
                    throw new Exception("Question paper is already assign to User, Please assign some other.");
                else
                {
                    using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                    {
                        using (SqlCommand cmd = new SqlCommand("usp_InsertNewStudentPaperDetail_Create", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@QPaperID", QPaperID);
                            cmd.Parameters.AddWithValue("@UserID", UserID);
                            cmd.Parameters.AddWithValue("@QPaperStatus", "Assigned");
                            using (SqlDataAdapter da = new SqlDataAdapter())
                            {
                                da.SelectCommand = cmd;
                                da.Fill(dtResult);
                            }
                        }
                    }
                    return Json("The question paper was assigned successfully to the User.");
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }
    }
}

Controllers/StudentExamController.cs
using ExaminationPortal.App_Start;
using ExaminationPortal.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace ExaminationPortal.Controllers
{
    public class StudentExamController : Controller
    {
        // GET: StudentExam
        [CheckSessionOutAttribute]
        public ActionResult Index(long StudentPaperDetailID)
        {
            var model = new StudentPaperDetailList();
            try
            {
                ViewBag.StudentPaperDetailID = StudentPaperDetailID;
                DataTable dtResult = new DataTable();
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetStudentPaperDetail", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@StudentPaperDetailID", StudentPaperDetailID);
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtResult);
                        }
                    }
                }

                if (dtResult.Rows.Count > 0)
                {
                    foreach (DataRow item in dtResult.Rows)
                    {
                        model.MappingList.Add(new StudentPaperDetail
                        {
                            StudentPaperDetailID = Convert.ToInt64(item["StudentPaperDetailID"]),
                            Time = Convert.ToString(item["Time"]) == "" ? 0 : Convert.ToInt64(item["Time"]),
                            QPaperName = Convert.ToString(item["QPaperName"]),
                            QuestionID = Convert.ToInt64(item["QuestionID"]),
                            Question = Convert.ToString(item["Question"]),
                            OptionA = Convert.ToString(item["OptionA"]),
                            OptionB = Convert.ToString(item["OptionB"]),
                            OptionC = Convert.ToString(item["OptionC"]),
                            OptionD = Convert.ToString(item["OptionD"]),
                            SubmittedAns = Convert.ToString(item["SubmittedAns"])
                        });
                    }
                    ViewBag.PaperName = dtResult.Rows[0]["QPaperName"];
                    return View(model);
                }
                else
                    return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        [CheckSessionOutAttribute]
        [HttpPost]
        public ActionResult SaveStudentPaperDetailAnswer(long StudentPaperDetailID, string questionids, string answers)
        {
            string[] que = questionids.Split(',');
            string[] ans = answers.Split(',');

            for (int i = 0; i < que.Count(); i++)
            {
                if (!String.IsNullOrEmpty(que[i]))
                {
                    using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                    {
                        con.Open();
                        using (SqlCommand cmd = new SqlCommand("usp_InsertStudentPaperDetailAnswer_Create", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@StudentPaperDetailID", StudentPaperDetailID);
                            cmd.Parameters.AddWithValue("@QuestionID", que[i]);
                            cmd.Parameters.AddWithValue("@SubmittedAns", ans[i]);
                            cmd.ExecuteNonQuery();
                        }
                        con.Close();
                    }
                }
            }

            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand("usp_UpdateStudentPaperDetail_Update", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@StudentPaperDetailID", StudentPaperDetailID);
                    cmd.ExecuteNonQuery();
                }
                con.Close();
            }

            return RedirectToAction("Index");
        }

        [CheckSessionOutAttribute]
        public ActionResult AssignedPaper()
        {
            try
            {
                DataTable dtResult = new DataTable();

                #region Get assigned paper list
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetAllStudentPaperDetailList_GetByUserID", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@UserID", Convert.ToInt64(Session["UserID"]));
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtResult);
                        }
                    }
                }
                #endregion

                #region Prepare data to rerurn into view
                if (dtResult != null && dtResult.Rows.Count > 0)
                {
                    List<StudentPaperDetail> list = (from dr in dtResult.AsEnumerable()
                                                     select new StudentPaperDetail()
                                                     {
                                                         StudentPaperDetailID = Convert.ToInt64(dr["StudentPaperDetailID"]),
                                                         QPaperID = Convert.ToInt64(dr["QPaperID"]),
                                                         UserID = Convert.ToInt64(dr["UserID"]),
                                                         QPaperStatus = dr["QPaperStatus"].ToString(),
                                                         UserName = dr["UserName"].ToString(),
                                                         PaperName = dr["QPaperName"].ToString(),
                                                         Marks = dr["Marks"] == DBNull.Value ? 0 : Convert.ToInt32(dr["Marks"]),
                                                         IsExamCompleted = dr["QPaperStatus"].ToString().Trim() == "Assigned" ? false : true
                                                     }).ToList();

                    return View("~/views/StudentExam/AssignedPaper.cshtml", list);
                }
                else
                    return View("~/views/StudentExam/AssignedPaper.cshtml", new List<StudentPaperDetail>());
                #endregion
            }
            catch (Exception ex)
            {
                return View("~/views/StudentExam/AssignedPaper.cshtml", new List<StudentPaperDetail>());
            }
        }
    }
}

Views/PaperAssignment/Index.cshtml
@model ExaminationPortal.Models.StudentPaperDetail
@{
    ViewBag.Title = "Student Paper";
}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<div class="form-horizontal">
    <h2>Student Paper Management</h2>
    <hr />
    <label class="text-danger" id="errorMessage"></label>
    <div class="form-group">
        <label class="control-label col-md-2">Student</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.UserIDs, (IEnumerable<SelectListItem>)ViewBag.StudentList as SelectList, new { @id = "ddlStudentList", @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Question Paper</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.QPaperIDs, (IEnumerable<SelectListItem>)ViewBag.QPaperList as SelectList, new { @id = "ddlQPaperList", @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="btnSave" type="button" value="Save" class="btn btn-primary" />
        </div>
    </div>
    <div class="form-group">
        <div class="table-auto">
            <table id="tblList" class="table table-responsive">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.UserName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaperName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.QPaperStatus)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Marks)
                        </th>
                        <th>Action</th>
                        <th hidden>
                            @Html.DisplayNameFor(model => model.UserID)
                        </th>
                        <th hidden>
                            @Html.DisplayNameFor(model => model.QPaperID)
                        </th>
                    </tr>
                </thead>
                @foreach (var item in Model.StudentPaperDetailList)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaperName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QPaperStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marks)
                </td>
                <td>
                    <a href='@Url.Action("Index", "StudentExam", new { StudentPaperDetailID = item.StudentPaperDetailID })'>Details</a>
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.UserID)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.QPaperID)
                </td>
            </tr>
                }
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#btnSave").click(function () { Save(); });
    });

    function Save() {
        $("#errorMessage").html("");

        var selectedStudentID = $("#ddlStudentList").val();
        var selectedQPaperID = $("#ddlQPaperList").val();
        if (selectedStudentID <= 0 || selectedStudentID == '' || selectedStudentID == null) {
            $("#errorMessage").html("Student is required.");
            return;
        }
        if (selectedQPaperID <= 0 || selectedQPaperID == '' || selectedQPaperID == null) {
            $("#errorMessage").html("Question Paper is required.");
            return;
        }

        var param = JSON.stringify({ 'UserID': selectedStudentID, 'QPaperID': selectedQPaperID });

        $.ajax({
            type: "POST",
            url: '@Url.Action("AssignPaperToStudent", "PaperAssignment")',
            data: param,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            async: false,
            success: function (response) {
                $("#errorMessage").html(response);
                window.setTimeout(function () {
                    location.reload();
                }, 5000);

            },
            error: function (response) {
                $("#errorMessage").html(response.responseText);
                window.setTimeout(function () {
                    location.reload();
                }, 5000);
            }
        });
    }
</script>