Models/QuestionPaper.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ExaminationPortal.Models
{
    public class QuestionPaper
    {
        public long QPaperID { get; set; }
        [Required]
        [DisplayName("Question Paper")]
        public string QPaperName { get; set; }

    }

    public class QPaperQBankMapping
    {
        public long QPaperID { get; set; }
        public string QPaperName { get; set; }
        public long QBankID { get; set; }
        public string QBankName { get; set; }
        public string QBankIDs { get; set; }
        public List<QPaperQBankMapping> QPaperQBankMappingList { get; set; }

        public QPaperQBankMapping()
        {
            QPaperQBankMappingList = new List<QPaperQBankMapping>();
            QBankIDs = string.Empty;
        }
    }
}

Controllers/QuestionPaperController.cs
using ExaminationPortal.App_Start;
using ExaminationPortal.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace ExaminationPortal.Controllers
{
    public class QuestionPaperController : Controller
    {
        #region Question Paper
        // GET: QuestionPaper
        [CheckSessionOutAttribute]
        public ActionResult Index()
        {
            try
            {
                DataTable dtResult = new DataTable();

                #region Get Questions list
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetAllQuestionPaperList_Get", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtResult);
                        }
                    }
                }
                #endregion

                #region Prepare data to rerurn into view
                if (dtResult != null && dtResult.Rows.Count > 0)
                {
                    List<QuestionPaper> questionBankList = (from dr in dtResult.AsEnumerable()
                                                            select new QuestionPaper()
                                                            {
                                                                QPaperID = Convert.ToInt64(dr["QPaperID"]),
                                                                QPaperName = dr["QPaperName"].ToString()
                                                            }).ToList();

                    return View("~/views/QuestionPaper/index.cshtml", questionBankList);
                }
                else
                    return View("~/views/QuestionPaper/index.cshtml", new List<QuestionPaper>());
                #endregion
            }
            catch (Exception ex)
            {
                return View("~/views/QuestionPaper/index.cshtml", new List<QuestionPaper>());
            }
        }

        [HttpGet]
        [CheckSessionOutAttribute]
        public ActionResult Create()
        {
            return View(new QuestionPaper());
        }

        [HttpPost]
        [CheckSessionOutAttribute]
        public ActionResult Create(QuestionPaper model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    #region Check Question Paper name Exists or Not
                    DataTable dt = new DataTable();
                    using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                    {
                        using (SqlCommand cmd = new SqlCommand("usp_CheckQuestionPapernameExists_GetByName", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@QPaperName", model.QPaperName);
                            using (SqlDataAdapter da = new SqlDataAdapter())
                            {
                                da.SelectCommand = cmd;
                                da.Fill(dt);
                            }
                        }
                    }
                    if (dt.Rows.Count > 0)
                        throw new Exception("Question Paper is already exists!!!");
                    #endregion

                    using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                    {
                        con.Open();
                        using (SqlCommand cmd = new SqlCommand("usp_InsertNewQuestionPaper_Create", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@QPaperName", model.QPaperName);
                            cmd.ExecuteNonQuery();
                        }
                        con.Close();
                    }
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        [CheckSessionOutAttribute]
        public ActionResult Edit(long id)
        {
            var model = new QuestionPaper();
            try
            {
                DataTable dtResult = new DataTable();
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetQuestionPaperRecord_GetByID", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@QPaperID", id);
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtResult);
                        }
                    }
                }

                if (dtResult.Rows.Count > 0)
                {
                    model.QPaperID = Convert.ToInt64(dtResult.Rows[0]["QPaperID"]);
                    model.QPaperName = dtResult.Rows[0]["QPaperName"].ToString();
                    return View(model);
                }
                else
                    return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        [HttpPost]
        [CheckSessionOutAttribute]
        public ActionResult Edit(long id, QuestionPaper model)
        {
            try
            {
                if (id <= 0)
                    throw new ArgumentException("QPaperID is invalid.");

                if (ModelState.IsValid)
                {
                    #region Check Question Bank name Exists or Not while updating
                    DataTable dt = new DataTable();
                    using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                    {
                        using (SqlCommand cmd = new SqlCommand("usp_CheckQuestionPapernameExistsWhileUpdate_GetByName", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@QPaperID", id);
                            cmd.Parameters.AddWithValue("@QPaperName", model.QPaperName);
                            using (SqlDataAdapter da = new SqlDataAdapter())
                            {
                                da.SelectCommand = cmd;
                                da.Fill(dt);
                            }
                        }
                    }
                    if (dt.Rows.Count > 0)
                        throw new Exception("Question Paper is already exists!!!");
                    #endregion

                    using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                    {
                        con.Open();
                        using (SqlCommand cmd = new SqlCommand("usp_UpdateQuestionPaper_Update", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@QPaperID", id);
                            cmd.Parameters.AddWithValue("@QPaperName", model.QPaperName);
                            cmd.ExecuteNonQuery();
                        }
                        con.Close();
                    }
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }
        #endregion

        [HttpGet]
        [CheckSessionOutAttribute]
        public ActionResult QPaperQBankMapping(long id, string name)
        {
            try
            {
                var model = new QPaperQBankMapping();
                DataTable dtQBankList = new DataTable();
                DataTable dtResult = new DataTable();

                #region Prepare dropdown data
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetQuestionBankListHaving4Ques_Get", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtQBankList);
                        }
                    }
                }
                ViewBag.QBankList = ToSelectList(dtQBankList, "QBankID", "QBankName");
                #endregion

                #region Get prepare list
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetPaperAndBankDetails_GetByPaperID", con))
                    {

Views/QuestionPaper/Create.cshtml
@model ExaminationPortal.Models.QuestionPaper
@{
    ViewBag.Title = "Create Question Paper";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Add a new Question Paper</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QPaperName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QPaperName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QPaperName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href="/QuestionPaper/Index" class="btn btn-default">Back to Question Paper</a>
</div>

Views/QuestionPaper/Edit.cshtml
@model ExaminationPortal.Models.QuestionPaper

@{
    ViewBag.Title = "Update Question Paper";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Update - Question Paper</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QPaperName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QPaperName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QPaperName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href="/QuestionPaper/Index" class="btn btn-default">Back to Question Paper</a>
</div>

Views/QuestionPaper/Index.cshtml
@model IEnumerable<ExaminationPortal.Models.QuestionPaper>
@{
    ViewBag.Title = "Question Paper";
}
<br />
<div class="mt-3">
    <a href="/QuestionPaper/Create/" class="btn btn-primary button">Add new Question Paper</a>
</div>
<br />
<div class="table-auto">
    <table class="table table-responsive">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.QPaperName)
                </th>
                <th>Action</th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.QPaperName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.QPaperID }) |
                    @Html.ActionLink("Map Question Bank", "QPaperQBankMapping", new { id = item.QPaperID, name = item.QPaperName })
                </td>
            </tr>
        }
    </table>
</div>

Views/QuestionPaper/QPaperQBankMapping.cshtml
@model ExaminationPortal.Models.QPaperQBankMapping
@{
    ViewBag.Title = "Mapping - Question Paper and Question Bank";
}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<div class="form-horizontal">
    <h2>Mapping - Question Paper and Question Bank</h2>
    <hr />
    <label class="text-danger" id="errorMessage"></label>
    <label class="text-success" id="successMessage"></label>
    <div class="form-group">
        <label class="control-label col-md-2">Question Bank List</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.QBankIDs, ViewBag.QBankList as SelectList, new { @id = "ddlQBankList", @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="btnAdd" type="button" value="Add" class="btn btn-primary" />
            <input id="btnSave" type="button" value="Save" class="btn btn-primary" />
        </div>
    </div>
    <div class="form-group">
        <table id="tblList" class="table table-responsive">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.QPaperName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.QBankName)
                    </th>
                    <th hidden>
                        @Html.DisplayNameFor(model => model.QBankID)
                    </th>
                </tr>
            </thead>
            @foreach (var item in Model.QPaperQBankMappingList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.QPaperName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QBankName)
                    </td>
                    <td hidden>
                        @Html.DisplayFor(modelItem => item.QBankID)
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<div>
    <a href="/QuestionPaper/Index" class="btn btn-default">Back to Question Paper</a>
</div>


<script>
    var selectQBankList = [];
    $(document).ready(function () {
        if (@ViewBag.IsAllQBankMapped == 1) {
            $("#btnAdd").attr("disabled", true);
            $("#btnSave").attr("disabled", true);
            $("#errorMessage").html("You have already mapped Question Bank with a Question Paper.");
        }
        $("#btnAdd").click(function () { Add(); });
        $("#btnSave").click(function () { Save(); });
    });

    function Add() {
        $("#errorMessage").html("");
        var selectedQBankID = $("#ddlQBankList").val();
        var selectedQBankText = $("#ddlQBankList option:selected").text();
        if ($.inArray(selectedQBankID, selectQBankList) >= 0) {
            $("#errorMessage").html("You have already have added Question Bank for mapping, Please select different one.");
            return;
        }
        selectQBankList.push(selectedQBankID);
        $('#tblList tr:last').after('<tr><td>@ViewBag.QPaperName</td><td> ' + selectedQBankText + ' </td><td hidden> ' + selectedQBankID + ' </td></tr>');
    }

    function Save() {
        $("#errorMessage").html("");
        if (selectQBankList.length > 4) {
            $("#errorMessage").html("You can add only 4 Question Bank with Paper.");
            return;
        } else if (selectQBankList.length <= 3) {
            $("#errorMessage").html("You must have to select minimum 4 Question Bank.");
            return;
        }
        var QuestionBankIDs = selectQBankList.join(",");
        var param = JSON.stringify({ 'QPaperID': @ViewBag.QPaperID, 'selectQBankList': QuestionBankIDs });

        $.ajax({
            type: "POST",
            url: '@Url.Action("QPaperQBankMappingSave", "QuestionPaper")',
            data: param,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            async: false,
            success: function (response) {
                $("#successMessage").html("Question bank was mapped successfully.");
                $("#errorMessage").html("");
                window.setTimeout(function () {
                    location.reload();
                }, 5000);

            },
            error: function (data) {
                $("#errorMessage").html("Something went wrong, please reload page and try again!!!");
                $("#successMessage").html("");
                window.setTimeout(function () {
                    location.reload();
                }, 5000);
            }
        });
    }
</script>