Models/QuestionBank.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ExaminationPortal.Models
{
    public class QuestionBank
    {
        public long QBankID { get; set; }

        public long QBankDetailID { get; set; }

        public long QuestionID { get; set; }

        [Required]
        [DisplayName("Question Bank")]
        public string QBankName { get; set; }
    }

    public class QBankAndQuestionMapping
    {
        public long Value { get; set; }
        public string Text { get; set; }
        public bool IsChecked { get; set; }
    }
    public class QBankAndQuestionMappingList
    {
        public List<QBankAndQuestionMapping> MappingList { get; set; }

        public QBankAndQuestionMappingList()
        {
            MappingList = new List<QBankAndQuestionMapping>();
        }
    }
}

Controllers/QuestionBankController.cs
using ExaminationPortal.App_Start;
using ExaminationPortal.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace ExaminationPortal.Controllers
{
    public class QuestionBankController : Controller
    {
        #region Question Bank
        [CheckSessionOutAttribute]
        public ActionResult Index()
        {
            try
            {
                DataTable dtResult = new DataTable();

                #region Get Questions list
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetAllQuestionBankList_Get", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtResult);
                        }
                    }
                }
                #endregion

                #region Prepare data to rerurn into view
                if (dtResult != null && dtResult.Rows.Count > 0)
                {
                    List<QuestionBank> questionBankList = (from dr in dtResult.AsEnumerable()
                                                           select new QuestionBank()
                                                           {
                                                               QBankID = Convert.ToInt64(dr["QBankID"]),
                                                               QBankName = dr["QBankName"].ToString()
                                                           }).ToList();

                    return View("~/views/QuestionBank/index.cshtml", questionBankList);
                }
                else
                    return View("~/views/QuestionBank/index.cshtml", new List<QuestionBank>());
                #endregion
            }
            catch (Exception ex)
            {
                return View("~/views/QuestionBank/index.cshtml", new List<QuestionBank>());
            }
        }

        [HttpGet]
        [CheckSessionOutAttribute]
        public ActionResult Create()
        {
            return View(new QuestionBank());
        }

        [HttpPost]
        [CheckSessionOutAttribute]
        public ActionResult Create(QuestionBank model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    #region Check Question Bank name Exists or Not
                    DataTable dt = new DataTable();
                    using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                    {
                        using (SqlCommand cmd = new SqlCommand("usp_CheckQuestionBanknameExists_GetByName", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@QBankName", model.QBankName);
                            using (SqlDataAdapter da = new SqlDataAdapter())
                            {
                                da.SelectCommand = cmd;
                                da.Fill(dt);
                            }
                        }
                    }
                    if (dt.Rows.Count > 0)
                        throw new Exception("Question Bank is already exists!!!");
                    #endregion

                    using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                    {
                        con.Open();
                        using (SqlCommand cmd = new SqlCommand("usp_InsertNewQuestionBank_Create", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@QBankName", model.QBankName);
                            cmd.ExecuteNonQuery();
                        }
                        con.Close();
                    }
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        [CheckSessionOutAttribute]
        public ActionResult Edit(int id)
        {
            var model = new QuestionBank();
            try
            {
                DataTable dtResult = new DataTable();
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetQuestionBankRecord_GetByID", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@QBankID", id);
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtResult);
                        }
                    }
                }

                if (dtResult.Rows.Count > 0)
                {
                    model.QBankID = Convert.ToInt64(dtResult.Rows[0]["QBankID"]);
                    model.QBankName = dtResult.Rows[0]["QBankName"].ToString();
                    return View(model);
                }
                else
                    return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        [HttpPost]
        [CheckSessionOutAttribute]
        public ActionResult Edit(int id, QuestionBank model)
        {
            try
            {
                if (id <= 0)
                    throw new ArgumentException("QBankID is invalid.");

                if (ModelState.IsValid)
                {
                    #region Check Question Bank name Exists or Not while updating
                    DataTable dt = new DataTable();
                    using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                    {
                        using (SqlCommand cmd = new SqlCommand("usp_CheckQuestionBanknameExistsWhileUpdate_GetByName", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@QBankID", id);
                            cmd.Parameters.AddWithValue("@QBankName", model.QBankName);
                            using (SqlDataAdapter da = new SqlDataAdapter())
                            {
                                da.SelectCommand = cmd;
                                da.Fill(dt);
                            }
                        }
                    }
                    if (dt.Rows.Count > 0)
                        throw new Exception("Question Bank is already exists!!!");
                    #endregion

                    using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                    {
                        con.Open();
                        using (SqlCommand cmd = new SqlCommand("usp_UpdateQuestionBank_Update", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@QBankID", id);
                            cmd.Parameters.AddWithValue("@QBankName", model.QBankName);
                            cmd.ExecuteNonQuery();
                        }
                        con.Close();
                    }
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }
        #endregion

        [CheckSessionOutAttribute]
        public ActionResult AddQBankAndQuestionMapping(long id)
        {
            var model = new QBankAndQuestionMappingList();
            try
            {
                DataTable dtResult = new DataTable();
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["dbConnection"].ToString()))
                {
                    using (SqlCommand cmd = new SqlCommand("usp_GetAllUnMappedQuestion_Get", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        using (SqlDataAdapter da = new SqlDataAdapter())
                        {
                            da.SelectCommand = cmd;
                            da.Fill(dtResult);
                        }
                    }
                }
                ViewBag.QBankID = id;

                if (dtResult.Rows.Count > 0)
                {
                    foreach (DataRow item in dtResult.Rows)
                    {
                        model.MappingList.Add(new QBankAndQuestionMapping
                        {
                            Value = Convert.ToInt64(item["QuestionID"]),
                            Text = item["Question"].ToString(),
                            IsChecked = false
                        });
                    }
                    return View(model);
                }
                else
                    return View(model);
            }
            catch (Exception ex)
            {

Views/QuestionBank/AddQBankAndQuestionMapping.cshtml
@model ExaminationPortal.Models.QBankAndQuestionMappingList
@{
    ViewBag.Title = "Mapping - Question Bank and Question";
}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2>Mapping - Question Bank and Question</h2>
    <hr />
    <label class="text-danger">Note: Select questions to map with Question Bank.</label><br />
    <label class="text-danger" id="errorMessage"></label>
    <div class="question-wrapper">
        @foreach (var item in Model.MappingList)
        {
            <div class="question-list">
                <input id="@(item.Value)"
                       type="checkbox"
                       value="@item.Value"
                       checked="@item.IsChecked" />
                @item.Text <br />
            </div>
        }
    </div>
</div>
    <hr />
    <div class="form-group">
        <div class="col-md-12 pl-0">
            <input type="button" id="btnSave" value="Save" class="btn btn-primary" />
        </div>
    </div>
    <br />
    <br />
    <br />
    <div>
        <a href="/QuestionBank/Index" class="btn btn-default">Back to Question Bank</a>
    </div>
}

<script>
    $(document).ready(function () {
        $("#btnSave").click(function () { Save(); });
    });

    function Save() {
        $("#errorMessage").html("");
        var selectedQuestions = [];

        if ($("input:checkbox").length == 0 || $("input:checkbox").length == undefined) {
            $("#errorMessage").html("No Questions found to map in Question Bank.");
            return;
        }

        $("input:checkbox").each(function () {
            var $this = $(this);
            if ($this.is(":checked")) {
                selectedQuestions.push($this.attr("id"));
            }
        });

        if (selectedQuestions.length <= 0) {
            $("#errorMessage").html("You must have to select atleast one Question.");
            return;
        }

        var QuestionIDs = selectedQuestions.join(",");
        var param = JSON.stringify({ 'QBankID': @ViewBag.QBankID, 'selectedQuestionsID': QuestionIDs});

        $.ajax({
            type: "POST",
            url: '@Url.Action("AddQBankAndQuestionMapping", "QuestionBank")',
            data: param,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            async: false,
            success: function (response) {
                window.location = "/QuestionBank/index";
            },
            error: function (data) {
                window.location = "/QuestionBank/index";
            }
        });
    }
</script>

Views/QuestionBank/Create.cshtml
@model ExaminationPortal.Models.QuestionBank

@{
    ViewBag.Title = "Create Question Bank";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Add a new Question Bank</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.QBankName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QBankName, new { htmlAttributes = new { @maxlength = "50", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QBankName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href="/QuestionBank/Index" class="btn btn-default">Back to Question Bank</a>
</div>

Views/QuestionBank/Edit.cshtml
@model ExaminationPortal.Models.QuestionBank


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Update - Question Bank</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.QBankName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QBankName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QBankName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href="/QuestionBank/Index" class="btn btn-default">Back to Question Bank</a>
</div>

Views/QuestionBank/Index.cshtml
@model IEnumerable<ExaminationPortal.Models.QuestionBank>
@{
    ViewBag.Title = "Question Bank";
}

<br />
<div class="mt-3">
    <a href="/QuestionBank/Create/" class="btn btn-primary button">Add new Question Bank</a>
</div>
<br />
<div class="table-auto">
    <table class="table table-responsive">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.QBankName)
                </th>
                <th>Action</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.QBankName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.QBankID }) |
                    @Html.ActionLink("Map Questions", "AddQBankAndQuestionMapping", new { id = item.QBankID })
                </td>
            </tr>
        }

    </table>
</div>